
plugin:
  name: croqo.lottie::lang.plugin.name
  description: croqo.lottie::lang.plugin.description
  author: Eugene Croquette
  icon: icon-play-circle
  homepage: https://github.com/croqo/oc-lottie-plugin
